UPLOADED_FILE_MAXIMUM_SIZE_ALLOWED = 26214400


RIGHT_SIDE_TOP = 6
LEFT_SIDE_BOTTOM = 8
BOTTOM_RIGHT_SIDE = 3

IMAGE_MAX_ALLOWED_WIDTH = 1200
EDITOR_IMAGE_MAX_WIDTH = 900
LARGE_THUMBNAIL_WIDTH = 270
LARGE_THUMBNAIL_HEIGHT = 180
SMALL_THUMBNAIL_WIDTH = 80
SMALL_THUMBNAIL_HEIGHT = 60
