
redirection_dict={
    'index.php':'/',
    'classroom.php':'classroom',
    'online-upsc-course.php':'online-upsc-course',
    'upsc-optional-subject-online-course.php':'upsc-optional-subject-online-course',
    'current-affairs-and-newspaper-course-for-upsc.php':'current-affairs-and-newspaper-course-for-upsc',
    'postal-courses.php':'upsc-postal-courses',
    'upsc-prelims-test-series.php':'upsc-prelims-test-series',
    'upsc-online-gs-mains-test-series.php':'upsc-online-gs-mains-test-series',
    'upsc-optional-test-series.php':'upsc-optional-test-series',
    'upsc-main-exam-crash-course.php':'upsc-main-exam-crash-course',
    'testseries.php':'upsc-prelims-and-mains-test-series',
    'interview.php':'upsc-interview-guidance-course',
    'prelims-test-series-syllabus-answer-keys-and-result.php':'prelims-test-series-syllabus-answer-keys-and-result',
    'upsc-classroom-gs-mains-test-series.php':'upsc-classroom-gs-mains-test-series',
    'general-2.php':'upcoming-courses-for-upsc-civil-services-examination',
    'chennai-classroom.php':'chennai-classroom',
    'best-ias-upsc-coaching-institute-in-delhi.php':'best-ias-upsc-coaching-institute-in-delhi',
    'current-affair-material.php':'upsc-current-affairs-material',
    'kurukshetra-summary.php':'kurukshetra-summary-for-upsc-cse',
    'yojana-summary.php':'yojana-summary-for-upsc-cse',
    'upsc-previous-papers.php':'upsc-previous-papers',
    'upsc-syllabus.php':'upsc-syllabus',
    'booklists.php':'booklists-for-upsc',
    'upsc-gs-postal-books.php':'upsc-gs-postal-books',
    'fee-structure.php':'fee-structure',
    'achievements.php':'ias-selections-from-vajiram',
    'contact.php':'contact',
    'faq.php':'faq',
    'blogs.php':'blogs',
    'online-ias-gs-course.php':'online-ias-gs-course',
    'online-ias-csat-course.php':'online-ias-csat-course',
    'how-to-take-vajiram-upsc-online-prelims-test-series.php':'how-to-take-vajiram-upsc-online-prelims-test-series',
    'about-us.php':'about-us',
    'disclaimer.php':'disclaimer',
    'terms-and-conditions.php':'terms-and-conditions',
    'privacy-and-policy.php':'privacy-policy',
    'handouts.php':'handouts',
    'courses.php':'courses',
    'general.php':'general-faqs',
    'careers.php':'careers',
    'vajiram-and-ravi-new-student-portal.php':'vajiram-and-ravi-new-student-portal',
    'vajiram-faqs.php':'vajiram-faqs',
    'how-to-prepare-for-upsc-civil-services-exam.php':'how-to-prepare-for-upsc-civil-services-exam',
    'general-1.php':'general-faqs-1',
    'upsc-booklist-best-books-for-upsc-exam.php':'upsc-booklist-best-books-for-upsc-exam',
    'accomodation-pg-near-vajiram.php':'accomodation-pg-near-vajiram',
    'upsc-prelims-strategy-dos-and-donts.php':'upsc-prelims-strategy-dos-and-donts',
    'upsc-civil-services-exam-pattern.php':'upsc-civil-services-exam-pattern',
    'how-to-choose-optional-subject-for-upsc-exam.php':'how-to-choose-optional-subject-for-upsc-exam',
    'how-to-prepare-for-the-upsc-civil-services-mains-exam.php':'how-to-prepare-for-the-upsc-civil-services-mains-exam',
    'how-to-study-current-affairs-for-upsc-preparation.php':'how-to-study-current-affairs-for-upsc-preparation',
    'how-to-join-vajiram-and-ravi-upsc-classroom-course.php':'how-to-join-vajiram-and-ravi-upsc-classroom-course',
    'faq-6.php':'upsc-cse-prelims-exam',
    'faq-7.php':'about-upsc-cse-mains-examination',
    'faq-8.php':'what-is-the-interview-personality-test-stage',
    'faq-9.php':'when-is-the-upsc-final-result-declared',
    'faq-10.php':'when-does-the-upsc-advertise-about-the-examination',
    'faq-11.php':'eligibiliy-criteria-for-upsc-cse-ias-exam',
    'faq-12.php':'age-limit-for-upsc-civil-services-examination',
    'faq-13.php':'maximum-attempts-allowed-for-upsc-cse',
    'faq-14.php':'number-of-vacancies-in-upsc-civil-services-examination',
    'faq-15.php':'competition-level-in-upsc-civil-services-examination',
    'faq-16.php':'schedule-of-the-civil-services-examination',
    'faq-17.php':'optional-subjects-for-upsc-cse-examination',
    'faq-18.php':'how-vajiram-and-ravi-helps-in-ias-examination',
    'faq-19.php':'batches-to-join-in-vajiram-and-ravi',
}

new_dict={'about-us.php': 'website:about_us',
 'accomodation-pg-near-vajiram.php': 'website:accomodation_pg_near_vajiram',
 'general-23.php': 'website:accomodation_pg_near_vajiram',
 'achievements.php': 'website:ias_selections_from_vajiram',
 'best-ias-upsc-coaching-institute-in-delhi.php': 'website:best_ias_upsc_coaching_institute_in_delhi',
 'blogs.php': 'website:blogs',

 'blogs/general-studies-books-for-upsc.php': 'website:general_studies_books_for_upsc',
 'upsc-books/public-administration-booklist-for-upsc.php': 'website:public_administration_booklist_for_upsc',
 'upsc-books/sociology-booklist-for-upsc.php': 'website:sociology_booklist_for_upsc',
 'upsc-books/history-booklist-for-upsc.php': 'website:history_booklist_for_upsc',
 'booklist-28.php': 'website:history_booklist_for_upsc',
 'upsc-philosophy-books.php': 'website:philosophy_booklist_for_upsc',
 'blogs/upsc-maths-optional-book.php': 'website:mathematics_booklist_for_upsc',
 'blogs/geography-books-for-upsc.php': 'website:geography_booklist_for_upsc',
 'blogs/anthropology-books-for-upsc-cse-mains.php': 'website:anthropology_booklist_for_upsc',
 'blogs/commerce-and-accountancy-upsc-books.php': 'website:commerce_and_accountancy_booklist_for_upsc',
 'blogs/upsc-political-science-books.php': 'website:political_science_booklist_for_upsc',
 'blogs/upsc-international-relations-books.php': 'website:international_relations_booklist_for_upsc',
 'blogs/how-to-prepare-governance-for-upsc-cse-mains.php': 'website:how_to_prepare_governance_for_upsc_cse_mains',
 'blogs/preparing-from-newspaper-editorials-for-upsc-ias.php': 'website:preparing_from_newspaper_editorials_for_upsc_ias',
 'blogs/world-history-preparation-for-upsc-ias.php': 'website:world_history_preparation_for_upsc_ias',
 'blogs/sociology-optional-for-upsc-ias.php': 'website:sociology_optional_for_upsc_ias',
 'blogs/how-to-prepare-from-yellow-books-for-upsc-ias.php': 'website:how_to_prepare_from_yellow_books_for_upsc_ias',
 'blogs/strategy-to-succeed-in-ias-mains-after-3-attempts.php': 'website:strategy_to_succeed_in_ias_mains_after_3_attempts',
 'blogs/how-to-study-maps-for-upsc-ias.php': 'website:how_to_study_maps_for_upsc_ias',
 'blogs/Self-Preparation-Strategy-for-UPSC-CSE.php': 'website:self_preparation_strategy_for_upsc_ias_civil_services_examination',
 'blogs/upsc-cse-interview-tips.php': 'website:upsc_cse_interview_tips',
 'blogs/philosophy-optional-subject-for-upsc.php': 'website:philosophy_optional_subject_for_upsc',
 'blogs/strategy-to-prepare-ethics-paper-for-upsc.php': 'website:strategy_to_prepare_ethics_paper_for_upsc',
 'blogs/prepare-forward-backward-linkages-from-the-hindu-for-upsc-current-affairs.php': 'website:prepare_forward_backward_linkages_from_the_hindu_for_upsc_current_affairs',
 'blogs/prepare-for-a-subject-without-any-background-for-upsc-cse.php': 'website:prepare_for_a_subject_without_any_background_for_upsc_cse',
 'blogs/maths-optional-for-upsc.php': 'website:maths_optional_for_upsc',
 'blogs/vajirao-ias-bajirav-ias-bajiram-ias-bajirao-ias.php': 'website:vajirao_ias_bajirav_ias_bajiram_ias_bajirao_ias',
 'blogs/civil-services-day.php': 'website:civil_services_day',
 


 'booklists.php': 'website:booklists_for_upsc',
 'careers.php': 'website:careers',
 'chennai-classroom.php': 'website:chennai_classroom',
 'classroom.php': 'website:classroom',
 'contact.php': 'website:contact',
 'courses.php': 'website:classroom',
 'current-affair-material.php': 'website:upsc_current_affairs_material',
 'current-affairs-and-newspaper-course-for-upsc.php': 'website:current_affairs_and_newspaper_course_for_upsc',
 'disclaimer.php': 'website:disclaimer',
 'faq-10.php': 'website:when_does_the_upsc_advertise_about_the_examination',
 'faq-11.php': 'website:eligibiliy_criteria_for_upsc_cse_ias_exam',
 'faq-12.php': 'website:age_limit_for_upsc_civil_services_examination',
 'faq-13.php': 'website:maximum_attempts_allowed_for_upsc_cse',
 'faq-14.php': 'website:number_of_vacancies_in_upsc_civil_services_examination',
 'faq-15.php': 'website:competition_level_in_upsc_civil_services_examination',
 'faq-16.php': 'website:schedule_of_the_civil_services_examination',
 'faq-17.php': 'website:optional_subjects_for_upsc_cse_examination',
 'faq-18.php': 'website:how_vajiram_and_ravi_helps_in_ias_examination',
 'faq-19.php': 'website:batches_to_join_in_vajiram_and_ravi',
 'faq-6.php': 'website:upsc_cse_prelims_exam',
 'faq-7.php': 'website:about_upsc_cse_mains_examination',
 'faq-8.php': 'website:what_is_the_interview_personality_test_stage',
 'faq-9.php': 'website:when_is_the_upsc_final_result_declared',
 'faq.php': 'website:faq',
 'fee-structure.php': 'website:fee_structure',
 'general-1.php': 'website:how_to_prepare_for_the_upsc_civil_services_mains_exam',
 'general-2.php': 'website:upcoming_courses_for_upsc_civil_services_examination',
 'general-3.php': 'website:how_to_join_vajiram_and_ravi_upsc_classroom_course',
 'admission-process-how-to-join-vajiram.php': 'website:how_to_join_vajiram_and_ravi_upsc_classroom_course',
 'general.php': 'website:general_faqs',
 'handouts.php': 'website:handouts',
 'how-to-choose-optional-subject-for-upsc-exam.php': 'website:how_to_choose_optional_subject_for_upsc_exam',
 'how-to-join-vajiram-and-ravi-upsc-classroom-course.php': 'website:how_to_join_vajiram_and_ravi_upsc_classroom_course',
 'how-to-prepare-for-the-upsc-civil-services-mains-exam.php': 'website:how_to_prepare_for_the_upsc_civil_services_mains_exam',
 'how-to-prepare-for-upsc-civil-services-exam.php': 'website:how_to_prepare_for_upsc_civil_services_exam',
 'how-to-study-current-affairs-for-upsc-preparation.php': 'website:how_to_study_current_affairs_for_upsc_preparation',
 'how-to-take-vajiram-upsc-online-prelims-test-series.php': 'website:how_to_take_vajiram_upsc_online_prelims_test_series',
 'index.php': 'website:/',
 'interview.php': 'website:upsc_interview_guidance_course',
 'kurukshetra-summary.php': 'website:kurukshetra_summary_for_upsc_cse',
 'online-ias-csat-course.php': 'website:online_ias_csat_course',
 'online-ias-gs-course.php': 'website:online_ias_gs_course',
 'online-upsc-course.php': 'website:online_upsc_course',
 'postal-courses.php': 'website:upsc_postal_courses',
 'prelims-test-series-syllabus-answer-keys-and-result.php': 'website:prelims_test_series_syllabus_answer_keys_and_result',
 'privacy-and-policy.php': 'website:privacy_policy',
 'terms-and-conditions.php': 'website:terms_and_conditions',
 'testseries.php': 'website:upsc_prelims_and_mains_test_series',
 'upsc-booklist-best-books-for-upsc-exam.php': 'website:upsc_booklist_best_books_for_upsc_exam',
 'upsc-civil-services-exam-pattern.php': 'website:upsc_civil_services_exam_pattern',
 'general-4.php': 'website:upsc_civil_services_exam_pattern',
 'upsc-classroom-gs-mains-test-series.php': 'website:upsc_classroom_gs_mains_test_series',
 'upsc-gs-postal-books.php': 'website:upsc_gs_postal_books',
 'upsc-main-exam-crash-course.php': 'website:upsc_main_exam_crash_course',
 'upsc-online-gs-mains-test-series.php': 'website:upsc_online_gs_mains_test_series',
 'upsc-optional-subject-online-course.php': 'website:upsc_optional_subject_online_course',
 'upsc-optional-test-series.php': 'website:upsc_optional_test_series',
 'upsc-prelims-strategy-dos-and-donts.php': 'website:upsc_prelims_strategy_dos_and_donts',
 'upsc-prelims-test-series.php': 'website:upsc_prelims_test_series',
 'upsc-previous-papers.php': 'website:upsc_previous_papers',
 'upsc-syllabus.php': 'website:upsc_syllabus',
 'faq-21.php': 'website:upsc_syllabus',
 'vajiram-and-ravi-new-student-portal.php': 'website:vajiram_and_ravi_new_student_portal',
 'vajiram-faqs.php': 'website:vajiram_faqs',
 'yojana-summary.php': 'website:yojana_summary_for_upsc_cse',
 'optional-subjects-for-upsc.php': 'website:optional_subjects_for_upsc',

 'course-29.php': 'website:public_administration_optional_subject',
 'course-30.php': 'website:geography_optional_subject',
 'course-31.php': 'website:sociology_optional_subject',
 'course-32.php': 'website:political_science_optional_subject',
 'course-33.php': 'website:psychology_optional_subject',
 'course-34.php': 'website:commerce_optional_subject',
 'course-41.php': 'website:anthropology_optional_subject',

 'course-40.php': 'website:history_optional_subject',
 
 'philosophy-optional-subject-for-upsc.php': 'website:philosophy_optional_subject_for_upsc',
 'political-science-optional-subject-for-upsc.php': 'website:political_science_optional_subject',
 'psychology-optional-subject-for-upsc.php': 'website:psychology_optional_subject',
 'sociology-optional-subject-for-upsc.php': 'website:sociology_optional_subject',
 'geography-optional-subject-for-upsc.php': 'website:geography_optional_subject',


 'history-optional-subject-for-upsc.php': 'website:history_optional_subject',
 'economics-optional-subject-for-upsc.php': 'website:upsc_optional_subject_online_course',
 'mathematics-optional-subject-for-upsc.php': 'website:maths_optional_for_upsc',

 }

# new_dict = 
# # for key, value in redirection_dict.items():
# #     slugged = value.replace("-","_")
# #     print(f"path(r'{value}/', \\\n\tTemplateView.as_view(template_name='website/{slugged}.html'), \\\n\tname='{slugged}'),\n")

# new_dict = {}
# for key, value in redirection_dict.items():
#     slugged = value.replace("-","_")
#     # new_dict[key] = f'website:{slugged}'
#     new_dict[key] = slugged
#     # print(f'website:{slugged}')