from django.contrib.sitemaps import Sitemap
from website.models import Page
from django.urls import reverse

class PageSitemap(Sitemap):
	changefreq = 'daily'
	priority = 0.5
	protocol="https"
	def items(self):
		return Page.objects.filter(is_active=True)


class StaticSitemap(Sitemap):
	changefreq = 'daily'
	priority = 0.5
	protocol="https"

	def items(self):
		return [\
			"website:home",
			# "website:truepush",
			"website:classroom",
			"website:online_ias_gs_course",
			"website:online_upsc_course",
			"website:upsc_optional_subject_online_course",
			"website:current_affairs_and_newspaper_course_for_upsc",
			"website:upsc_postal_courses",
			"website:upsc_prelims_test_series",
			"website:upsc_online_gs_mains_test_series",
			"website:upsc_optional_test_series",
			"website:online_ias_gs_course",
			"website:upsc_main_exam_crash_course",
			"website:upsc_prelims_and_mains_test_series",
			"website:upsc_interview_guidance_course",
			"website:prelims_test_series_syllabus_answer_keys_and_result",
			"website:upsc_classroom_gs_mains_test_series",
			"website:upcoming_courses_for_upsc_civil_services_examination",
			"website:vajiram_and_ravi_fee_structure_for_upsc_courses",
			"website:how_to_take_vajiram_upsc_online_prelims_test_series",
			"website:chennai_classroom",
			"website:online_ias_csat_course",
			"website:best_ias_upsc_coaching_institute_in_delhi",
			"website:upsc_current_affairs_material",
			"website:kurukshetra_summary_for_upsc_cse",
			"website:yojana_summary_for_upsc_cse",
			"website:upsc_previous_papers",
			"website:upsc_syllabus",
			"website:booklists_for_upsc",
			"website:upsc_gs_postal_books",
			"website:fee_structure",
			"website:ias_selections_from_vajiram",
			"website:contact",
			"website:faq",
			"website:blogs",
			"website:general_studies_books_for_upsc",
			"website:public_administration_booklist_for_upsc",
			"website:sociology_booklist_for_upsc",
			"website:history_booklist_for_upsc",
			"website:philosophy_booklist_for_upsc",
			"website:mathematics_booklist_for_upsc",
			"website:geography_booklist_for_upsc",
			"website:anthropology_booklist_for_upsc",
			"website:commerce_and_accountancy_booklist_for_upsc",
			"website:political_science_booklist_for_upsc",
			"website:international_relations_booklist_for_upsc",
			"website:how_to_prepare_governance_for_upsc_cse_mains",
			"website:preparing_from_newspaper_editorials_for_upsc_ias",
			"website:world_history_preparation_for_upsc_ias",
			"website:sociology_optional_for_upsc_ias",
			"website:how_to_prepare_from_yellow_books_for_upsc_ias",
			"website:strategy_to_succeed_in_ias_mains_after_3_attempts",
			"website:how_to_study_maps_for_upsc_ias",
			"website:self_preparation_strategy_for_upsc_ias_civil_services_examination",
			"website:current_affairs_magazine_the_recitals",
			"website:upsc_cse_interview_tips",
			"website:philosophy_optional_subject_for_upsc",
			"website:strategy_to_prepare_ethics_paper_for_upsc",
			"website:prepare_forward_backward_linkages_from_the_hindu_for_upsc_current_affairs",
			"website:prepare_for_a_subject_without_any_background_for_upsc_cse",
			"website:maths_optional_for_upsc",
			"website:vajirao_ias_bajirav_ias_bajiram_ias_bajirao_ias",
			"website:civil_services_day",
			"website:about_us",
			"website:disclaimer",
			"website:terms_and_conditions",
			"website:privacy_policy",
			"website:handouts",
			"website:courses",
			"website:general_faqs",
			"website:careers",
			"website:vajiram_and_ravi_new_student_portal",
			"website:vajiram_faqs",
			"website:how_to_prepare_for_upsc_civil_services_exam",
			"website:upsc_booklist_best_books_for_upsc_exam",
			"website:accomodation_pg_near_vajiram",
			"website:upsc_prelims_strategy_dos_and_donts",
			"website:upsc_civil_services_exam_pattern",
			"website:how_to_choose_optional_subject_for_upsc_exam",
			"website:how_to_prepare_for_the_upsc_civil_services_mains_exam",
			"website:how_to_study_current_affairs_for_upsc_preparation",
			"website:how_to_join_vajiram_and_ravi_upsc_classroom_course",
			"website:upsc_cse_prelims_exam",
			"website:about_upsc_cse_mains_examination",
			"website:what_is_the_interview_personality_test_stage",
			"website:when_is_the_upsc_final_result_declared",
			"website:when_does_the_upsc_advertise_about_the_examination",
			"website:eligibiliy_criteria_for_upsc_cse_ias_exam",
			"website:age_limit_for_upsc_civil_services_examination",
			"website:maximum_attempts_allowed_for_upsc_cse",
			"website:number_of_vacancies_in_upsc_civil_services_examination",
			"website:competition_level_in_upsc_civil_services_examination",
			"website:schedule_of_the_civil_services_examination",
			"website:optional_subjects_for_upsc_cse_examination",
			"website:how_vajiram_and_ravi_helps_in_ias_examination",
			"website:batches_to_join_in_vajiram_and_ravi",
			"website:optional_subjects_for_upsc",
			"website:public_administration_optional_subject",
			"website:geography_optional_subject",
			"website:sociology_optional_subject",
			"website:political_science_optional_subject",
			"website:psychology_optional_subject",
			"website:commerce_optional_subject",
			"website:anthropology_optional_subject",
			"website:history_optional_subject",
			"website:economics_optional_subject",
		]

	def location(self, item):
		return reverse(item)